# Generated by Django 5.1.2 on 2024-11-05 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("value", models.DecimalField(decimal_places=8, max_digits=30)),
            ],
        ),
        migrations.CreateModel(
            name="AnswerSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
