# Generated by Django 5.1.2 on 2024-11-05 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("answers", "0001_initial"),
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="choice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exams.choice"
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exams.question"
            ),
        ),
        migrations.AddField(
            model_name="answersheet",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exams.exam"
            ),
        ),
    ]
