# Generated by Django 5.1.2 on 2024-11-05 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("answers", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="answersheet",
            name="examinee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="answer_sheet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="answers.answersheet"
            ),
        ),
    ]
