# Generated by Django 5.1.2 on 2024-11-02 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('solution_description', models.TextField()),
                ('marks', models.IntegerField()),
                ('time_limit', models.DurationField()),
                ('solution_text', models.TextField()),
                ('solution_value', models.DecimalField(decimal_places=8, max_digits=30)),
                ('type', models.CharField(choices=[('MC', 'Multiple Choice'), ('TXT', 'Text Answer'), ('NUM', 'Numerical')], default='MC', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('choice_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_correct', models.BooleanField(default=False)),
                ('multi_choice_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choices', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage_text', models.TextField()),
                ('passage_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.exam')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.questiongroup'),
        ),
    ]
