# Generated by Django 5.1.2 on 2024-11-05 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exams", "0001_initial"),
        ("questions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="questions.level"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="questions.subject"
            ),
        ),
        migrations.AddField(
            model_name="choice",
            name="multi_choice_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="choices",
                to="exams.question",
            ),
        ),
        migrations.AddField(
            model_name="questiongroup",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exams.exam"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="exams.questiongroup"
            ),
        ),
    ]
