# Generated by Django 5.1.2 on 2024-10-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('vacancies', models.IntegerField()),
                ('responsibilities', models.TextField()),
                ('job_type', models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CT', 'Contract'), ('IS', 'Intern')], default='FT', max_length=20)),
                ('time_commitment', models.CharField(max_length=100)),
                ('remuneration', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('required_qualifications', models.TextField()),
                ('preferred_qualifications', models.TextField()),
                ('deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
