# Generated by Django 5.1.2 on 2024-11-09 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0002_subject_teachers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="teachers",
            field=models.ManyToManyField(
                blank=True, related_name="subjects", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
